### ISSUE TITLE
BilibiliAudioGet-1.03是不是失效了？

### ISSUE THREAD

**Issue by oicqbak** [LXG-Shadow/BilibiliTools#2]
测试（无法下载）：https://www.bilibili.com/audio/au1020538?type=3

另外默认格式m4a，能自动转换为MP3（320k）吗？

**Comment by aynakeya** [comment]
我目前测试没有失效。
请你确定使用了正确的命令。
audio https://www.bilibili.com/audio/au1020538?type=3

**Comment by aynakeya** [comment]
暂时没有转换为mp3的功能。之后会加入到bilibiliDownloader里。这个可能不会更新了。
